project:
  type: website
  resources:
    - css/**
    - js/**
    - images/**

website:
  title: "Sabrina Minaya"
  navbar:
    left:
      - text: "Home"
        href: "#slides"
      - text: "About"
        href: "#about"
      - text: "Skills"
        href: "#skills"
      - text: "Projects"
        href: "#portafolio"
      - text: "Contact"
        href: "#contact-info"

format:
  html:
    theme: none
    include-in-header: includes/head.html
    include-after-body: includes/after-body.html

